apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/data-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: django-pv
---
apiVersion: v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  selector:
    matchLabels:
      app: django-deployment
  template:
    metadata:
      labels:
        app: django-deployment
spec:
  containers:
    - name: atiq-django-container
      image: iatiqul/django-todo-django
      env:
        - name: SECRET_KEY
          value: '8)810zj@#^2xp=1=2rkozbv8#)gub6m1a^9qf&)d-9&x9*c2a_'
        - name: DATABASE_NAME
          value: 'todo'
        - name: DATABASE_USER
          value: 'root'
        - name: DATABASE_PASSWORD
          value: 'djangotodo'
        - name: DATABASE_HOST
          value: '10.106.117.251'
        - name: DATABASE_PORT
          value: '3306'
#---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-deployment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
#    nodePort: 30006
  type: ClusterIP
